stages:
  prepare:
    cmd: C:\ProgramData\anaconda3\python.exe src/prepare.py
    deps:
      - src/prepare.py
      - data/telecomchurn.csv
    params:
      - prepare
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: C:\ProgramData\anaconda3\python.exe src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
    params:
      - train
    outs:
      - models/model.pkl

  evaluate:
    cmd: C:\ProgramData\anaconda3\python.exe src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/test.csv
      - models/model.pkl
    params:
      - evaluate
    metrics:
      - metrics.json:
          cache: false